name: Trigger Credentials Update

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    name: Trigger Credentials Update
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to renew auth credentials
        run: |
          curl --request POST \
          --url 'https://qatar22.vercel.app/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'